---
# =============================================================================
# Ansible Role: Package Update - Tasks: Reboot
# =============================================================================
# Managed reboot after package updates.
# =============================================================================

- name: Package-Update | reboot | Reboot system and wait until available
  become: true
  ansible.builtin.reboot:
    msg: "{{ package_update_reboot_message | default('Reboot initialized by Ansible') }}"
    connect_timeout: "{{ package_update_reboot_connect_timeout | default('60') | int }}"
    reboot_timeout: "{{ package_update_reboot_wait_timeout | default('300') | int }}"
    pre_reboot_delay: "{{ package_update_reboot_wait_delay | default('10') | int }}"
    post_reboot_delay: "{{ (package_update_reboot_interval | default(true)) | ternary(package_update_reboot_interval_seconds | default('10'), 0) | int }}"
  register: __package_update_reboot_result
  when: >
    package_update_reboot_wait | default(true)

# Justification: Use shell module to trigger reboot asynchronously without blocking/waiting because the native reboot module requires waiting for the host to come back.
- name: Package-Update | reboot | Trigger reboot without waiting
  become: true
  ansible.builtin.shell: |
    sleep 2 && shutdown -r now "{{ package_update_reboot_message | default('Reboot initialized by Ansible') }}"
  async: 1
  poll: 0
  changed_when: false
  failed_when: false
  when: >
    not (package_update_reboot_wait | default(true))

- name: Package-Update | reboot | Report reboot completion time
  ansible.builtin.debug:
    msg: "The system rebooted in {{ __package_update_reboot_result.elapsed }} seconds."
  when: >
    __package_update_reboot_result is defined
