# =============================================================================
# Ansible Role: Package-Update - Molecule Convergence Playbook
# =============================================================================
# This playbook executes the main role functionality in the test environment.
# It performs the following steps:
# - Updates package repositories
# - Ensures system readiness
# - Executes the Package-Update role with test configuration
#
# Flow:
# 1. Update package cache
# 2. Wait for system initialization
# 3. Apply Package-Update role with test variables
# =============================================================================

---
# -----------------------------------------------------------------------------
# 1. Pre-Tasks Setup
# -----------------------------------------------------------------------------
- name: molecule | Converge
  hosts: all

  pre_tasks:
    # Package Cache Update
    - name: Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: >
        ansible_facts['os_family'] == "Debian"

    - name: Converge | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: >
        ansible_facts['os_family'] == "RedHat"

    # System Initialization
    - name: Converge | Wait for systemd to complete initialization
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: >
        ansible_facts['service_mgr'] == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

# -----------------------------------------------------------------------------
# 2. Role Execution with Test Variables
# -----------------------------------------------------------------------------
  vars:
    # Test configuration for Package-Update role
    package_update_enabled: true
    package_update_update_cache: true
    package_update_upgrade_type: "dist"
    package_update_autoremove: true
    package_update_autoclean: true

    # Test reboot settings
    package_update_reboot_enabled: false
    package_update_reboot_timeout: 600

  roles:
    - role: grzegorzfranus.package_update
