---
# Package-Update Molecule — Converge for default scenario.

- name: Molecule | Converge
  hosts: all

  pre_tasks:
    - name: Converge | Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: Converge | Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when:
        - ansible_facts['os_family'] == "RedHat"

    - name: Converge | Wait for systemd to complete initialization
      ansible.builtin.systemd:
        name: multi-user.target
        state: started
      register: __systemctl_status
      until: true
      retries: 30
      delay: 5
      when:
        - ansible_facts['service_mgr'] == 'systemd'
      changed_when: false
      failed_when: false

  vars:
    package_update_role_action: "all"
    package_update_mode: "all"
    package_update_display_upgradable_packages: true
    package_update_log_upgradable_packages: false
    package_update_disk_space_check_enabled: false

  roles:
    - role: ../../..

  post_tasks:
    - name: Converge | Display role execution summary
      ansible.builtin.debug:
        msg: "Package-Update role execution completed"
