---
# Package-Update Molecule — Prepare test environment.

- name: Molecule | Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Prepare | Fix /etc/shadow permissions
      ansible.builtin.file:
        path: /etc/shadow
        mode: "0400"
